name: benchmark

on:
  schedule:
    - cron:  '*/10 * * * *'
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to load'
        default: 'https://enisyst.de'
        required: true

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install openvpn
        run: sudo apt install openvpn -y
      - name: start openvpn
        timeout-minutes: 5
        run: |
          echo "${{ secrets.CLIENT_CONF }}" > client.conf
          echo "${{ secrets.CLIENT_CRT }}" > client.crt
          echo "${{ secrets.CLIENT_KEY }}" > client.key
          echo "${{ secrets.TA_CLS_KEY }}" > ta-cls.key
          echo "${{ secrets.CLS_CRT }}" > cls.crt
          sudo openvpn --config client.conf --log openvpn.log --daemon
          until ping -c1 10.36.36.7; do sleep 1; done
      - name: install selenium 
        run: |
          pip install selenium
      - name: manual benchmark
        if: github.event.inputs.url != ''
        run: |
          python benchmark.py --url ${{ github.event.inputs.url }} >> history.csv
      - name: scheduled benchmark
        if: github.event.inputs.url == ''
        run: |
          python benchmark.py --url https://10.36.36.7:10512/dist/index.html >> history.csv
          python benchmark.py --url https://eniserv.de/pliezhausen/dist/index.html >> history.csv
      - name: commit result
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Added new benchmark for ${{ github.event.inputs.url }}"
          git push
      - name: stop openvpn
        if: always()
        run: sudo killall openvpn
      - name: prepare logs
        if: always()
        run: sudo chmod 777 openvpn.log
      - name: save logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: '*.log'
          retention-days: 5
