name: manual trigger

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to load'
        default: 'https://enisyst.de'
        required: true

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install selenium 
        run: |
          pip install selenium
      - name: benchmark
        run: |
          python benchmark.py --url ${{ github.event.inputs.url }} >> history.csv
      - name: commit result
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Added new benchmark for ${{ github.event.inputs.url }}"
          git push
